github:
  email: "104018155+hmcts-dependency-updater[bot]@users.noreply.github.com"
  user: "hmcts-dependency-updater"
  branch: "main"
  owner: "hmcts"
  repository: "aks-cft-deploy"
environments:
  sbox:
    enabled: true
    aks_name: cft-sbox-01-aks
    aks_resource_group: cft-sbox-01-rg
    aks_subscription: DCD-CFTAPPS-SBOX
  ## Do not change demo to 01
  demo:
    enabled: true
    aks_name: cft-demo-00-aks
    aks_resource_group: cft-demo-00-rg
    aks_subscription: DCD-CFTAPPS-DEMO
  ## Do not change preview to 01
  preview:
    enabled: true
    aks_name: cft-preview-00-aks
    aks_resource_group: cft-preview-00-rg
    aks_subscription: DCD-CFTAPPS-DEV
  ithc:
    enabled: true
    aks_name: cft-ithc-00-aks
    aks_resource_group: cft-ithc-00-rg
    aks_subscription: DCD-CFTAPPS-ITHC
  ptlsbox:
    enabled: true
    aks_name: cft-ptlsbox-00-aks
    aks_resource_group: cft-ptlsbox-00-rg
    aks_subscription: DTS-CFTSBOX-INTSVC
  ptl:
    enabled: true
    aks_name: cft-ptl-00-aks
    aks_resource_group: cft-ptl-00-rg
    aks_subscription: DTS-CFTPTL-INTSVC
  aat:
    enabled: true
    aks_name: cft-aat-00-aks
    aks_resource_group: cft-aat-00-rg
    aks_subscription: DCD-CFTAPPS-STG
  perftest:
    enabled: true
    aks_name: cft-perftest-00-aks
    aks_resource_group: cft-perftest-00-rg
    aks_subscription: DCD-CFTAPPS-TEST
  prod:
    enabled: true
    aks_name: cft-prod-00-aks
    aks_resource_group: cft-prod-00-rg
    aks_subscription: DCD-CFTAPPS-PROD
