name: updatecli

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: '0 2 * * 1'  # Every monday at 2am UTC

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: b430ef1e-4e79-4e92-a152-8e5b5bc195d4        # DTS CFT AKS version checker
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082        # HMCTS.NET
          subscription-id: a8140a9e-f1b0-481f-a4de-09e2ee23f7ab  # DTS-SHAREDSERVICES-SBOX

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
        with:
          version: v0.35.1

      - name: Install YQ
        uses: mikefarah/yq@master

      - name: Run Updatecli in Dry Run mode
        run: |
          yq '.environments' updatecli/values.github-action.yaml | cut -d "-" -f 2 | while read i
          do
              CURRENT_ITER_ENVIRONMENT="$i" updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
          done
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/main'
        run: |
          yq '.environments' updatecli/values.github-action.yaml | cut -d "-" -f 2 | while read i
          do
              CURRENT_ITER_ENVIRONMENT="$i" updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
          done
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
